/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import kotlin.test.Test
import kotlin.test.assertTrue

class AppTest {
    @Test fun testEnvironmentLoads() {
        assertTrue(true)
    }
}
